<JoystickScreen>
    ImageButton:
        id: image_button
        center_x: 0.5 * root.width
        center_y: 0.5 * root.height
        on_press: root.switch_screen_main()
    Label:
        id: pressed_label
        color: 0,0,0,1
        center_x: 0
        center_y: 0.5 * root.height
        text: "No Buttons Pressed"
    Label:
        id: x_pos
        color: 0,0,0,1
        center_x: -0.4 * root.width
        center_y: 0.5 * root.height
        text: "xxx"
    Label:
        id: y_pos
        color: 0,0,0,1
        center_x: 0.4 * root.width
        center_y: 0.5 * root.height
        text: "yyy"